# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

base:
  outputs:

    dev:
      type: postgres
      host: "{{ mage_secret_var('POSTGRES_HOST') }}"
      user: "{{ mage_secret_var('POSTGRES_USER') }}"
      pass: "{{ mage_secret_var('POSTGRES_PASSWORD') }}"
      port: "{{ mage_secret_var('POSTGRES_PORT') }}"
      dbname: "{{ mage_secret_var('POSTGRES_DB') }}"
      schema: analytics
      threads: 4

  target: dev
